- README.md
I hope I'm doing this right ;)
> Added new TinyMob jobs to the list

- README.md
Please add our job posting.  Thank you so much.
> added Growth Hacker posting

- README.md
I heard we were doing spellcheck.. so I'm jumping on the bandwagon
> correct some typos (nothing critical)

- README.md
Also added current Zynga Victoria job openings
> Added Zynga Canada

- README.md
Change.org does not currently have job postings for Victoria.
> Remove Change.org job postings

- README.md
Remove Benevity Front End Web Developer position.
Add Benevity UX Designer position.
> Update Benevity Job Postings

- README.md
> Benevity job listing changes

- README.md
Added Visual Designer job posting.
> Updated README.md - Added Job Posting for Referral SaaSquatch

- README.md
Added Hololabs to the job board (with one open position)
> Added job posting for Hololabs

- README.md
PxU us hiring! We've added a link to our careers page.
> Add PxU job posting

- README.md
Added new posting, and updated old link.
> Update SparkLit Job Postings

- README.md
Add Benevity positions: software developer, platform developer, and senior platform developer.
> Add additional Benevity positions

- README.md
We have a new job posting we'd like to add to the repo.
> Add new posting from AggregateIQ

- README.md
Removed Visual Designer as position is filled.
> Removed Posting for Referral SaaSquatch

- README.md
Removed some old postings, added a new one, and updated an old URL.
> Updated Redbrick's postings

- README.md
Added posting for Eclipse Creative Front-End Developer
> Added Front-End Developer Position

- README.md
Remove roles that have been filled: Insights Analyst, UX/UI Developer, and Senior Software Developer Platform.
Add new openings: Visual Designer, Manager Marketing Automation, and Senior Quality Assurance Analyst.
> Update Benevity Jobs

- README.md
> Removed Eclipse Position

- README.md
Adding [Clixxa](https://www.clixxa.com) jobs in Victoria BC
[Development Manager](https://jobs.lever.co/ctr/8c88eb77-f780-4457-96ce-224f77890488)
[DevOps Engineer](https://jobs.lever.co/ctr/f48bb48b-20a1-431f-a83f-0e62c746cfb5)
> adding Clixxa jobs in Victoria BC

- README.md
The latest Workday updates. Thanks!!
> Update open Workday job opportunities.

- README.md
Removing two positions and adding one for a golang developer
> Updating Clixxa job postings

- link_checker/README.md
- link_checker/check.py
- link_checker/requirements.txt
cc @bvanvugt don't say I didn't warn you
> Script to check jobs listing links for 404s, etc

- README.md
- link_checker/check.py
- link_checker/requirements.txt
This is ok because we're not using the content of the page for any purpose, so there's no concern with MITM attacks, etc.
> Fixes SSL certificate verification errors, by simply NOT validating.

- README.md
To keep things simple, we previously merged the open posting and no posting list together, I thought we could add the co-op friendly list with the main list as well.
> Merge Co-Op / Intern Friendly list with Main list.

- README.md
The latest Workday posting. Cheers!
> Add new Workday Jr. Dev Posting

- README.md
> removed our old job, put new ones in the right place

- README.md
Added LeapXD posting for Senior Front-End Dev
> Added LeapXD posting for Senior Front-End Dev

- README.md
Added Futurepet's Full Stack Developer posting
> Update README.MD to include FuturePet

- README.md
New job posting for Sasquatch Studio as of March 4, 2018
> Added Sasquatch Studio Job

- README.md
> Added Echosec software developer job

- README.md
> Add Barnacle Systems posting

- README.md
New PM job posting at https://jobs.lever.co/semaphoresolutions/2ef30c50-5ec1-48fd-9239-efbe821f390a
> Add new job posting for Semaphore Solutions

- README.md
> add fullstack job posting from Pretio

- README.md
Adding Victoria, BC Change.org open tech positions. Thanks!
> Adding Change.org open positions

- README.md
> Fix SaaSqatch link syntax

- README.md
Waterworth is hiring a full stack developer!
Financial advisor position will likely follow soon :)
> Add Waterworth full stack dev posting

- README.md
tried to run the link_checker but after a few minutes of various issues I decided I'd just let it run on the PR - will fix any issues if they come up.
> Add Waterworth CSM job

- README.md
- link_checker/check.py
- link_checker/requirements.txt
Pulling in the recent bambora PR and adding some fixes to hopefully improve Travis CI testing.
> Bambora plus fixes

- README.md
- removed old jobs (Web developer, UX Specialist)
- posted new Project Manager / Business Analyst job
- (extra commit to revert auto prettier-formatting)
> Updating itgroove job list

- README.md
Added developer position to Benevity
> Update README.md with Benevity position

- README.md
Added Computer Engineer job position for North Robotics
> Added North Robotics job position

- README.md
Accurate as of Oct 2019 with new Contract Position postings
> Update Bambora Job Posting

- README.md
- link_checker/check.py
Hey, I hope this contribution is helpful. Advanced Solutions isn't really a startup, but they do have a lot of tech jobs in Victoria. I'm also not in HR, just a employee who's looking for quality coworkers.
I'm happy to be a contact for anyone wanting more info before they apply or to help answer questions.
> Advanced Solutions - 2019-10-22

- README.md
Addresses broken dxcas.com link in https://github.com/sendwithus/vic-startup-jobs/pull/183/files
> Revela job plus fix

- README.md
Position specifies Calgary, but is open to the Victoria office. Position
also specifies "IT & Coporate Systems" team, but it's for the SRE team.
Creating PR again as the link checker is intermittently showing bad links locally, but not consistently.
> Add Benevity SRE Position

- README.md
Added SRE Platform (contract)
Added SRE Infra
Updated dev posting
> Bambora SRE updates

- README.md
Leaving Revela, but closing the job posting.
> Posting closed!

- README.md
Job postings for Gearbox Development 🎉
> Gearbox Development job postings

- README.md
Great to have this startup job board. Thank you!
> Added Audette Frontend Developer Job Posting

- README.md
> Removed Audette's Frontend Dev Posting

- README.md
Full disclosure: we're not technically a tech startup "with offices in Victoria BC" as the README states this job board is for, but we're a remote-only company with (currently) 100% of our workforce here in Victoria, so I assume that counts as close enough. 🙂
> Add Super Good Software developer positions

- README.md
> Add OneFeather Intermediate dev job

- README.md
> OneFeather position has been filled!

- README.md
Added Audette's Software Developer position
> Audette.io, Software Developer, July 1st 2020

- README.md
[Revela's](https://www.revela.io/) posting for a cloud focused developer is closed, but we're still managing to open another posting! This time for a junior / intern **Data Engineer**
> Data Engineer Posting at Revela

- README.md
Remove CSM position - filled
Add new positions
> Update Checkfront postings for September 2020

- README.md
Add Implementation Specialist position at Checkfront, and rename the Growth Developer position to match the listing.
Remove closed Cuboh postings, add new postings.
> Update Checkfront and Cuboh positions

- README.md
> Added One Net Jobs

- README.md
Hi there, we would love to add our posting for a Microsoft 365 Developer at Regroove Solutions. Thanks team!
> Add Regroove posting

- README.md
Remove filled positions, add some new ones
> Update Checkfront job postings for Jan 2021

- README.md
Removed postings that no longer exist, updated some others
> Remove broken and missing links; Update some postings

- README.md
Hopefully properly this time, sorry to @alannadare about not responding to the old one, we found someone pretty quickly and it wasn't needed— until now!
Fluorescent Design Inc is a remote company but over half our team lives and works in Victoria and we'd ideally like to hire another local. This listing is for a front end developer.
Thanks!
> Add Fluorescent posting

- README.md
Added jobs for One Net + Hipster Bait
> One Net + Hipster Bait jobs

- README.md
Added: Audette - Head of Software
> Audette - Head of Software

- README.md
> Added back-end dev posting

- README.md
> Add OneFeather Intermediate Developer job

- README.md
Adding the latest postings for Echosec. Thanks!
> Add Echosec's latest postings

- README.md
Figured I would clean up some of these expired postings while I'm here.
> Remove some expired job postings

- README.md
Add Course Studio url and post project manager position
> Add Course Studio url and post project manager position

- README.md
Removes some filled positions with Benevity and adds a few more.
> Clean up Benevity postings

- README.md
- Update Checkfront postings for May 2022
- Remove any other expired postings on the board
> Update Checkfront Postings for May 2022

- README.md
> chore: add software dev at Revela

- README.md
Change the URL in README to new rebranded landing page.
> Change Sendwithus URL in Readme

- README.md
- Update Checkfront Postings
- Remove other expired postings
> Update Checkfront Postings

- README.md
> Post Front-End Developer role

- README.md
We've closed these openings for now.
> Remove Super Good openings

- README.md
> Updating with 4 new roles at Othershere

- README.md
> Remove expired job listings

- README.md
Company is Montreal-based, but has a satellite office in Victoria.
> Add t0.technology.
